(autoload 'delicious-sync-posts                 "delicious" "" t)
(autoload 'delicious-post                       "delicious" "" t)
(autoload 'delicious-post-offline               "delicious" "" t)
(autoload 'delicious-post-cache                 "delicious" "" t)
(autoload 'delicious-clear-cache                "delicious" "" t)
(autoload 'delicious-rename-tag                 "delicious" "" t)
(autoload 'delicious-delete-href-post           "delicious" "" t)
(autoload 'delicious-w3m-bookmark-recent        "delicious" "" t)
(autoload 'delicious-w3m-export                 "delicious" "" t)
(autoload 'delicious-search-mode                "delicious" "" t)
(autoload 'delicious-search-browse-url          "delicious" "" t)
(autoload 'delicious-search-next-result         "delicious" "" t)
(autoload 'delicious-search-previous-result     "delicious" "" t)
(autoload 'delicious-search-copy-url            "delicious" "" t)
(autoload 'delicious-search-delete              "delicious" "" t)
(autoload 'delicious-search-add-tags            "delicious" "" t)
(autoload 'delicious-search-delete-tags         "delicious" "" t)
(autoload 'delicious-search-edit-extended       "delicious" "" t)
(autoload 'delicious-search-posts-regexp        "delicious" "" t)
(autoload 'delicious-search-description-regexp  "delicious" "" t)
(autoload 'delicious-search-href-regexp         "delicious" "" t)
(autoload 'delicious-search-tags                "delicious" "" t)
(autoload 'delicious-search-tags-any            "delicious" "" t)
(autoload 'delicious-search-date                "delicious" "" t)
(autoload 'delicious-search-hash                "delicious" "" t)

(provide 'delicious-epkg-install)
